site_name: Siddhi-MAP-TCP
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi MAP XML: index.md
- About:
  - License: about/license.md
- Api:
  - 4.0.0-M10-SNAPSHOT: api/4.0.0-M10-SNAPSHOT.md
  - 4.0.0-M9-SNAPSHOT: api/4.0.0-M9-SNAPSHOT.md
  - 4.0.0-M8: api/4.0.0-M8.md
- API Docs:
  - 4.0.0-M8: api/4.0.0-M8.md
  - 4.0.0-M9-SNAPSHOT: api/4.0.0-M9-SNAPSHOT.md
  - 4.0.0-M10-SNAPSHOT: api/4.0.0-M10-SNAPSHOT.md
theme: material
